[package]
name = "make_gds_migrate_list"
version = "0.1.0"
edition = "2021"

default-run = "make_gds_migrate_list"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
