[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Victor San Kho Lin <victor@sankholin.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
